version: '2'
services:
  spark-master:
    image: spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./spark/conf/master:/conf
      - ./spark/data:/tmp/data

  spark-worker-1:
    image: spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./spark/conf/worker:/conf
      - ./spark/data:/tmp/data

  zeppelin:
    image: zeppelin:latest
    command: bin/zeppelin.sh --config /conf
    hostname: zeppelin
    environment:
      ZEPPELIN_PORT: 8000
      SPARK_MASTER: spark://spark-master:7077
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    links:
      - spark-master
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./zeppelin/notebook:/notebook
      - ./zeppelin/conf:/conf

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-web:
    image: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    links:
      - postgres
      - spark-master
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8180:8180"
    command: webserver
