master:
  image: spark:latest
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./spark/conf/master:/conf
    - ./spark/data:/tmp/data

worker:
  image: spark:latest
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./spark/conf/worker:/conf
    - ./spark/data:/tmp/data

zeppelin:
  image: zeppelin:latest
  command: bin/zeppelin.sh --config /conf
  hostname: zeppelin
  environment:
    ZEPPELIN_PORT: 8000
    SPARK_MASTER: spark://master:7077
    ZEPPELIN_NOTEBOOK_DIR: /notebook
  links:
    - master
  expose:
    - 8000
  ports:
    - 8000:8000
  volumes:
    - ./zeppelin/notebook:/notebook
    - ./zeppelin/conf:/conf
